version: '3'
services:
  svc1:
    build: ./svc1/
    ports:
      - "8080:80"
    environment:
      - SERVICE_TWO_URL=svc2:80
  svc2:
    build: ./svc2/
    ports:
      - "8081:80"
    environment:
      - SERVICE_THREE_URL=svc3:80
  svc3:
    build: ./svc2/
    ports:
      - "8082:80"
