{{- if .Values.skeleton }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
    - http:
        paths:
          - path: /.*
            backend:
              serviceName: {{ template "helloworldtelephone.svc1.fullname" . }}
              servicePort: 80
{{- end }}
