apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "helloworldtelephone.svc2.fullname" . }}
  labels:
    app: {{ template "helloworldtelephone.name" . }}
    chart: {{ template "helloworldtelephone.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    svc: {{ .Values.svc2.name }}
spec:
  replicas: {{ .Values.replicatCount }}
  selector:
    matchLabels:
      app: {{ template "helloworldtelephone.name" . }}
      release: {{ .Release.Name }}
      svc: {{ .Values.svc2.name }}
  template:
    metadata:
      labels:
        app: {{ template "helloworldtelephone.name" . }}
        release: {{ .Release.Name }}
        svc: {{ .Values.svc2.name }}
    spec:
      containers:
        - name: {{ .Values.svc2.name }}
          image: "{{ .Values.svc2.image.repository }}:{{ .Values.svc2.image.tag }}"
          imagePullPolicy: {{ .Values.svc2.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.svc2.port }}
          env:
            - name: SERVICE_THREE_URL
              value: {{ template "helloworldtelephone.svc3.fullname" . }}
