{{- if .Values.skeleton }}
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: svc2routerule
spec:
  destination:
    name: {{ .Values.svc2.name  }}
  route:
    - labels:
        release: {{ .Values.blue.name }}
      weight: {{ .Values.blue.weight }}
    - labels:
        release: {{ .Values.green.name }}
      weight: {{ .Values.green.weight }}
{{- end }}
