{{- if .Values.skeleton }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc3.name }}
  labels:
    app: {{ template "helloworldtelephone.name" . }}
    chart: {{ template "helloworldtelephone.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    svc: {{ .Values.svc3.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.svc3.port }}
  selector:
    app: {{ template "helloworldtelephone.name" . }}
    svc: {{ .Values.svc3.name }}
{{- end }}
