# Default values for helloworldtelephone.

replicaCount: 1

# When skeleton is set, that means we want just
# the base components created and configured. This
# will be an entirely different release then the blue
# or green deployments. But when skeleton is false,
# then we are interested in deploying the bits... or
# the "meat" of the application (either blue or green)
skeleton: false

svc1:
  name: svc1
  image:
    repository: trstringer/hwtsvc1
    tag: 0.1.0
    pullPolicy: Always
  port: 80

svc2:
  name: svc2
  image:
    repository: trstringer/hwtsvc2
    tag: 0.1.0
    pullPolicy: Always
  port: 80

svc3:
  name: svc3
  image:
    repository: trstringer/hwtsvc3
    tag: 0.1.0
    pullPolicy: Always
  port: 80
