apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: svc2deployment
  labels:
    app: svc2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc2
  template:
    metadata:
      labels:
        app: svc2
    spec:
      containers:
        - name: svc2
          image: trstringer/hwtsvc2:latest
          ports:
            - containerPort: 80
