apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: svc3deployment
  labels:
    app: svc3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc3
  template:
    metadata:
      labels:
        app: svc3
    spec:
      containers:
        - name: svc3
          image: trstringer/hwtsvc3:latest
          ports:
            - containerPort: 80
